name: Continous Integration and Deployment

on:
  push:
    branches:
      - master

env:
  DOTNET_VERSION: '8.0.x'
  AZURE_WEBAPP_NAME: rm-hotel-api

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore dependencies
        run: dotnet restore
  
      - name: Build app
        run: dotnet build -c Release --no-restore

      - name: Publish app
        run: dotnet publish -c Release -o ./out

      - name: Deploy to Azure Web Apps
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_SECRET }}
          package: ./out